<a href="https://colab.research.google.com/github/FOYEJ1027/Simulation-Modeling-Lab/blob/main/1027Assignment03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name: Md. Mosaddek Hasan Foyej

ID : 0432310005101027

Basic Matrix Operations

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Create two 3×3 matrices
M1 = np.random.randint(0, 10, (3, 3))
M2 = np.random.randint(0, 10, (3, 3))

# Addition
sum_mat = M1 + M2

# Subtraction
diff_mat = M1 - M2

# Multiplication
prod_mat = np.dot(M1, M2)

print("Matrix M1:\n", M1)
print("\nMatrix M2:\n", M2)

print("\nAddition:\n", sum_mat)
print("\nSubtraction:\n", diff_mat)
print("\nMultiplication:\n", prod_mat)


# Determinant of M2
det_val = np.linalg.det(M2)

# Inverse
if det_val != 0:
    inv_mat = np.linalg.inv(M2)
else:
    inv_mat = "Matrix is Singular, cannot compute"

# Rank
rank_val = np.linalg.matrix_rank(M2)

print("\nDeterminant of Matrix M2:", det_val)
print("\nInverse Matrix:\n", inv_mat)
print("\nRank of Matrix M2:", rank_val)


Matrix M1:
 [[3 5 8]
 [0 5 8]
 [2 9 4]]

Matrix M2:
 [[7 9 3]
 [5 6 7]
 [1 6 8]]

Addition:
 [[10 14 11]
 [ 5 11 15]
 [ 3 15 12]]

Subtraction:
 [[-4 -4  5]
 [-5 -1  1]
 [ 1  3 -4]]

Multiplication:
 [[ 54 105 108]
 [ 33  78  99]
 [ 63  96 101]]

Determinant of Matrix M2: -183.00000000000009

Inverse Matrix:
 [[-0.03278689  0.29508197 -0.24590164]
 [ 0.18032787 -0.28961749  0.18579235]
 [-0.13114754  0.18032787  0.01639344]]

Rank of Matrix M2: 3


Matrix Plotting and
Visualization

In [ ]:
# Create two vectors with 15 random floats
vec_a = np.random.rand(15)
vec_b = np.random.rand(15)

plt.figure()
plt.plot(vec_a, marker='o', label='Vector A')
plt.plot(vec_b, marker='s', label='Vector B')

plt.xlabel("Index")
plt.ylabel("Value")
plt.title("Comparison of Two Random Vectors")
plt.legend()

plt.show()


In [ ]:
# Create 4x4 matrix
heat_matrix = np.random.rand(4, 4)

# Heatmap
sns.heatmap(
    heat_matrix,
    annot=True,
    cmap='copper',
    linewidths=1,
    linecolor='white'
)

plt.title('Heatmap of 4x4 Matrix')
plt.xlabel("Column Index")
plt.ylabel("Row Index")
plt.show()


In [ ]:
# Create two 4x4 matrices
MatX = np.random.rand(4, 4)
MatY = np.random.rand(4, 4)

# Operations
sum_result = MatX + MatY
diff_result = MatX - MatY
prod_result = np.dot(MatX, MatY)

# Plotting
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Addition
axes[0].bar(range(1, 17), sum_result.flatten(), color='blue')
axes[0].set_title('Matrix Addition')
axes[0].set_xlabel('Index')
axes[0].set_ylabel('Value')

# Subtraction
axes[1].bar(range(1, 17), diff_result.flatten(), color='green')
axes[1].set_title('Matrix Subtraction')
axes[1].set_xlabel('Index')
axes[1].set_ylabel('Value')

# Multiplication
axes[2].bar(range(1, 17), prod_result.flatten(), color='purple')
axes[2].set_title('Matrix Multiplication')
axes[2].set_xlabel('Index')
axes[2].set_ylabel('Value')

plt.tight_layout()
plt.show()
