<a href="https://colab.research.google.com/github/FOYEJ1027/Simulation-Modeling-Lab/blob/main/Copy_of_assignment_02_roll_1027.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Md. Mosaddek hasan foyej
Id : 0432310005101027(7-A2)

My Personal Matrix
Let:

d1 = last digit of your student ID

d2 = second last digit of your student ID

Create the matrix:

A =
[ d1 + 2  d2 + 1 ]
[ 2d1   d2 + 2 ]

In [ ]:
import numpy as np

d1 = 7
d2 = 2

A = np.array([[d1 + 2, d2 + 1],
              [2 * d1, d2 + 2]])

shape = A.shape
determinant = np.linalg.det(A)
rank = np.linalg.matrix_rank(A)
eigenvalues = np.linalg.eigvals(A)

print("Matrix A:\n", A)
print("Shape:", shape)
print("Determinant:", determinant)
print("Rank:", rank)
print("Eigenvalues:", eigenvalues)

if determinant != 0:
    inverse = np.linalg.inv(A)
    print("Inverse:\n", inverse)
else:
    print("Inverse: Not possible")

Matrix A:
 [[ 9  3]
 [14  4]]
Shape: (2, 2)
Determinant: -6.000000000000003
Rank: 2
Eigenvalues: [13.44622199 -0.44622199]
Inverse:
 [[-0.66666667  0.5       ]
 [ 2.33333333 -1.5       ]]


Analyze Matrix A
Using NumPy, compute:
● Shape of A
● Determinant
● Rank
● Eigenvalues
● Inverse (only if determinant ≠ 0)

In [ ]:
import numpy as np

d1 = 7
d2 = 2

# Step 1: Original matrix A
A = np.array([[d1+2, d2+1], [2*d1, d2+2]])
print("Original matrix A:\n", A)

# Step 2 (Question 3): Create matrix B by changing ONE element
B = A.copy()
B[0, 0] = B[0, 0] + 1
print("\n[Q3] Changed element: A[0,0] (top-left) by adding +1")
print("New matrix B:\n", B)

# Step 3 (Question 4): Re-analyze matrix B
print("\n[Q4] Analysis of matrix B:")

print("shape of matrix B is: ", B.shape)
print("determinant of B: ", np.linalg.det(B))
print("rank of matrix B is: ", np.linalg.matrix_rank(B))
print("eigen values: ", np.linalg.eigvals(B))

det_B = np.linalg.det(B)
if abs(det_B) > 1e-10:
    print("inverse of matrix B is:\n", np.linalg.inv(B))
else:
    print("determinant is zero , inverse does not exist")

Original matrix A:
 [[ 9  3]
 [14  4]]

[Q3] Changed element: A[0,0] (top-left) by adding +1
New matrix B:
 [[10  3]
 [14  4]]

[Q4] Analysis of matrix B:
shape of matrix B is:  (2, 2)
determinant of B:  -2.000000000000005
rank of matrix B is:  2
eigen values:  [14.14142843 -0.14142843]
inverse of matrix B is:
 [[-2.   1.5]
 [ 7.  -5. ]]
